name: auditllm
channels:
  - pytorch-nightly
  - plotly
  - conda-forge
  - defaults
dependencies:
  - accelerate=0.29.2
  - numpy=1.26.4
  - pandas=2.2.1
  - pingouin=0.5.4
  - plotly=5.21.0
  - python=3.9.19
  - pytorch=2.4.0.dev20240609
  - scipy=1.13.0
  - statsmodels=0.14.1
  - tokenizers=0.19.1
  - transformers=4.41.2
